#!/bin/sh
set -e
# Automatically added by dh_icons/13.11.4
if command -v update-icon-caches >/dev/null; then
	update-icon-caches /usr/share/icons/Adwaita /usr/share/icons/myshutdown.png /usr/share/icons/start.svg
fi
# End automatically added section
